export const FETCH_STUDENT_INFO_SUCCESS = "FETCH_STUDENT_INFO_SUCCESS";
export const FETCH_STUDENT_INFO_START = "FETCH_STUDENT_INFO_START";
export const FETCH_STUDENT_INFO_ERROR = "FETCH_STUDENT_INFO_ERROR";

export const FETCH_USER_INFO_SUCCESS = "FETCH_USER_INFO_SUCCESS";
export const FETCH_USER_INFO_START = "FETCH_USER_INFO_START";
export const FETCH_USER_INFO_ERROR = "FETCH_USER_INFO_ERROR";

export const FETCH_MY_GROUP_INFO_SUCCESS = "FETCH_STUDENT_INFO_SUCCESS";
export const FETCH_MY_GROUP_INFO_START = "FETCH_STUDENT_INFO_START";
export const FETCH_MY_GROUP_INFO_ERROR = "FETCH_STUDENT_INFO_ERROR";

export const FETCH_TEACHER_INFO_SUCCESS = "FETCH_TEACHER_INFO_SUCCESS";
export const FETCH_TEACHER_INFO_START = "FETCH_TEACHER_INFO_START";
export const FETCH_TEACHER_INFO_ERROR = "FETCH_TEACHER_INFO_ERROR";

export const FETCH_ALL_TEACHERS_SUCCESS = "FETCH_ALL_TEACHERS_SUCCESS";
export const FETCH_ALL_TEACHERS_START = "FETCH_ALL_TEACHERS_START";
export const FETCH_ALL_TEACHERS_ERROR = "FETCH_ALL_TEACHERS_ERROR";

export const FETCH_TEACHER_BY_ID_SUCCESS = "FETCH_TEACHER_BY_ID_SUCCESS";
export const FETCH_TEACHER_BY_ID_START = "FETCH_TEACHER_BY_ID_START";
export const FETCH_TEACHER_BY_ID_ERROR = "FETCH_TEACHER_BY_ID_ERROR";

export const FETCH_ALL_SUBJECTS_SUCCESS = "FETCH_ALL_SUBJECTS_SUCCESS";
export const FETCH_ALL_SUBJECTS_START = "FETCH_ALL_SUBJECTS_START";
export const FETCH_ALL_SUBJECTS_ERROR = "FETCH_ALL_SUBJECTS_ERROR";

export const FETCH_ALL_STUDENTS_SUCCESS = "FETCH_ALL_STUDENTS_SUCCESS";
export const FETCH_ALL_STUDENTS_START = "FETCH_ALL_STUDENTS_START";
export const FETCH_ALL_STUDENTS_ERROR = "FETCH_ALL_STUDENTS_ERROR";

export const LOGIN_AS_STUDENT_SUCCESS = "LOGIN_AS_STUDENT_SUCCESS";
export const LOGIN_AS_STUDENT_START = "LOGIN_AS_STUDENT_START";
export const LOGIN_AS_STUDENT_ERROR = "LOGIN_AS_STUDENT_ERROR";

export const LOGIN_AS_TEACHER_SUCCESS = "LOGIN_AS_TEACHER_SUCCESS";
export const LOGIN_AS_TEACHER_START = "LOGIN_AS_TEACHER_START";
export const LOGIN_AS_TEACHER_ERROR = "LOGIN_AS_TEACHER_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const SIGN_UP_USER_SUCCESS = "SIGN_UP_USER_SUCCESS";
export const SIGN_UP_USER_START = "SIGN_UP_USER_START";
export const SIGN_UP_USER_ERROR = "SIGN_UP_USER_ERROR";

export const FETCH_TODOS_START = 'FETCH_TODOS_START';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR';

export const ADD_TODOS_START = 'ADD_TODOS_START';
export const ADD_TODOS_SUCCESS = 'ADD_TODOS_SUCCESS';
export const ADD_TODOS_ERROR = 'ADD_TODOS_ERROR';

export const REMOVE_TODOS_START = 'REMOVE_TODOS_START';
export const REMOVE_TODOS_SUCCESS = 'REMOVE_TODOS_SUCCESS';
export const REMOVE_TODOS_ERROR = 'REMOVE_TODOS_ERROR';

